"""End-to-end verification of the full log -> insight loop.

Drives the real FastAPI app in-process (httpx ASGITransport, no network) against
a LOCAL/test database and asserts the whole loop produces sensible insights:

    1.  create a throwaway user (dev UUID-as-token auth shortcut)
    2.  POST /users/me/seed-priors          (cold-start onboarding priors)
    3.  POST /foods/decompose               (free-text meal -> ingredients)
    4.  POST /meals + /meals/{id}/items     (log a hand-tuned trigger diary)
    5.  POST /symptoms                      (log symptoms after trigger meals)
    6.  GET  /insights/suspect-foods        (planted trigger must top the board)
    7.  GET  /insights/triggers             (cold-start/​data-driven predictions)
    8.  GET  /insights/lag-correlation      (food<->symptom lag buckets)
    9.  POST /protocols/start               (elimination protocol)
    10. GET  /reports/clinician-pdf         (a real PDF is produced)

The diary is generated by ``seed_demo_account.build_demo_diary`` so this test
also proves the DEMO diary itself yields clear suspect-food signals. Prints a
PASS/FAIL summary and exits non-zero on any failure.

This script NEVER touches production: it forces the dev auth shortcut
(``SUPABASE_JWT_SECRET``/``SUPABASE_URL`` empty) and defaults to the local
``foodai_test`` database. Override with ``--db-url`` for another *local* DB.

Usage:
    python -m scripts.verify_e2e_loop
    python -m scripts.verify_e2e_loop --db-url postgresql+asyncpg://USER@localhost/foodai_test
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import os
import sys
import uuid
from datetime import UTC, datetime, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

_DEFAULT_DB_URL = "postgresql+asyncpg://matthewsouthard@localhost/foodai_test"
_DEFAULT_KB_PATH = (
    Path(__file__).resolve().parent.parent / "data" / "allergen_knowledge_base_complete.json"
)

# Deterministic throwaway E2E user (delete-first each run → idempotent).
E2E_NAMESPACE = uuid.UUID("e2ee2ee2-0000-4000-8000-000000000000")
E2E_USER_ID = uuid.uuid5(E2E_NAMESPACE, "verify_e2e_loop")
E2E_EMAIL = "verify_e2e@foodai.demo"


class Check:
    """Accumulates PASS/FAIL results for a readable summary."""

    def __init__(self) -> None:
        self.results: list[tuple[bool, str, str]] = []

    def record(self, ok: bool, name: str, detail: str = "") -> bool:
        self.results.append((bool(ok), name, detail))
        mark = "PASS" if ok else "FAIL"
        print(f"  [{mark}] {name}" + (f" — {detail}" if detail else ""))
        return ok

    @property
    def all_passed(self) -> bool:
        return all(ok for ok, _, _ in self.results)

    def summary(self) -> str:
        n_pass = sum(1 for ok, _, _ in self.results if ok)
        return f"{n_pass}/{len(self.results)} checks passed"


async def _reset_user(async_session_factory) -> None:
    from sqlalchemy import delete

    from app.models.user import User

    async with async_session_factory() as session:
        await session.execute(delete(User).where(User.id == E2E_USER_ID))
        await session.execute(delete(User).where(User.email == E2E_EMAIL))
        # Insert the user so the dev UUID-as-token auth shortcut can resolve it.
        session.add(User(id=E2E_USER_ID, email=E2E_EMAIL, onboarding_completed=True))
        await session.commit()


async def run_e2e(db_url: str, kb_path: str) -> int:
    # Force local dev auth shortcut + target DB BEFORE importing the app.
    os.environ["DATABASE_URL"] = db_url
    os.environ["APP_ENV"] = "development"
    os.environ["SUPABASE_JWT_SECRET"] = ""
    os.environ["SUPABASE_URL"] = ""
    os.environ.setdefault("ADMIN_API_KEY", "e2e-admin-key")

    from app.config import get_settings

    get_settings.cache_clear()

    from httpx import ASGITransport, AsyncClient
    from sqlalchemy import text

    import app.models  # noqa: F401 — register ORM models for create_all
    from app.database import Base, async_session_factory, engine
    from app.main import app
    from app.services.synthetic_data_generator import load_kb_food_index

    # echo=True (dev engine) forces the engine logger to INFO at creation; quiet
    # it now that the engine exists so the PASS/FAIL summary stays legible.
    logging.getLogger("sqlalchemy.engine").setLevel(logging.WARNING)

    # Ensure schema exists (idempotent on an already-migrated local DB).
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    await _reset_user(async_session_factory)

    # Build a hand-tuned trigger diary from the DEMO builder (demo_ibs spec).
    from scripts.seed_demo_account import DEMO_COHORT, build_demo_diary

    spec = next(s for s in DEMO_COHORT if s.slug == "demo_ibs")
    _, safe_foods = load_kb_food_index(kb_path)
    start_date = datetime.now(UTC) - timedelta(weeks=4)
    diary = build_demo_diary(spec, safe_foods, start_date=start_date, num_weeks=4)
    primary_trigger = spec.trigger_foods[0]  # "Garlic"

    check = Check()
    headers = {"Authorization": f"Bearer {E2E_USER_ID}"}

    print("\n" + "=" * 64)
    print("E2E LOG -> INSIGHT LOOP VERIFICATION")
    print(f"  DB:   {_redact(db_url)}")
    print(f"  user: {E2E_USER_ID}")
    print(f"  planted trigger: {primary_trigger} ({spec.trigger_component})")
    print("=" * 64)

    async with AsyncClient(
        transport=ASGITransport(app=app), base_url="http://test", headers=headers
    ) as ac:
        # ── 2. seed cold-start priors ──────────────────────────────────────
        r = await ac.post(
            "/api/v1/users/me/seed-priors", json={"conditions": spec.conditions}
        )
        seeded_detail = r.json().get("seeded") if r.status_code == 201 else r.text[:80]
        check.record(
            r.status_code == 201 and r.json().get("seeded", 0) >= 1,
            "POST /users/me/seed-priors",
            f"status={r.status_code} seeded={seeded_detail}",
        )

        # ── 3. text meal decomposition ─────────────────────────────────────
        r = await ac.post(
            "/api/v1/foods/decompose",
            json={"meal_text": "grilled chicken with garlic and white rice"},
        )
        decomp_ok = r.status_code == 200 and len(r.json().get("ingredients", [])) >= 2
        check.record(
            decomp_ok,
            "POST /foods/decompose (text meal)",
            f"status={r.status_code} ingredients="
            f"{len(r.json().get('ingredients', [])) if r.status_code == 200 else r.text[:80]}",
        )

        # ── 4. log the diary meals + items ─────────────────────────────────
        meals_logged = 0
        items_posted = 0
        a_trigger_meal_id: str | None = None
        for meal_data in diary["meals"]:
            mr = await ac.post(
                "/api/v1/meals",
                json={
                    "timestamp": meal_data["timestamp"].isoformat(),
                    "meal_type": meal_data["meal_type"].value,
                    "raw_description": meal_data["raw_description"],
                },
            )
            if mr.status_code != 201:
                continue
            meal_id = mr.json()["id"]
            meals_logged += 1
            items_payload = {"items": [{"name": f["name"]} for f in meal_data["foods"]]}
            ir = await ac.post(f"/api/v1/meals/{meal_id}/items", json=items_payload)
            if ir.status_code == 201:
                items_posted += len(items_payload["items"])
                if a_trigger_meal_id is None and any(
                    f["name"] == primary_trigger for f in meal_data["foods"]
                ):
                    a_trigger_meal_id = meal_id
        # Verify items actually PERSISTED via a fresh GET (the POST response body
        # can be empty due to an identity-map quirk in the items endpoint, but the
        # rows are committed — confirm the durable state, not the echo).
        gr = await ac.get(f"/api/v1/meals/{a_trigger_meal_id}")
        persisted_items = gr.json().get("items", []) if gr.status_code == 200 else []
        check.record(
            meals_logged == len(diary["meals"])
            and items_posted > 0
            and len(persisted_items) >= 1
            and any(i["name"] == primary_trigger for i in persisted_items),
            "POST /meals + /meals/{id}/items (persisted)",
            f"meals={meals_logged}/{len(diary['meals'])} items_posted={items_posted} "
            f"persisted_on_sample_meal={len(persisted_items)}",
        )

        # ── 5. log symptoms ────────────────────────────────────────────────
        symptoms_logged = 0
        for sym in diary["symptoms"]:
            sr = await ac.post(
                "/api/v1/symptoms",
                json={
                    "timestamp": sym["timestamp"].isoformat(),
                    "symptom_type": sym["symptom_type"].value,
                    "vas_score": int(sym["vas_score"]),
                },
            )
            if sr.status_code == 201:
                symptoms_logged += 1
        check.record(
            symptoms_logged == len(diary["symptoms"]),
            "POST /symptoms",
            f"symptoms={symptoms_logged}/{len(diary['symptoms'])}",
        )

        # ── 6. suspect foods — the planted trigger must top the board ───────
        r = await ac.get("/api/v1/insights/suspect-foods?lookback_days=45")
        foods = r.json().get("foods", []) if r.status_code == 200 else []
        top = foods[0] if foods else {}
        check.record(
            r.status_code == 200 and top.get("food_name") == primary_trigger,
            "GET /insights/suspect-foods (planted trigger is #1)",
            (
                f"top={top.get('food_name')} score={top.get('combined_score')} "
                f"episodes={top.get('n_symptom_episodes')} conf={top.get('confidence_label')}"
                if foods
                else f"status={r.status_code} no foods"
            ),
        )
        # Secondary trigger should also appear in the leaderboard.
        names = {f["food_name"] for f in foods}
        check.record(
            spec.trigger_foods[1] in names,
            "GET /insights/suspect-foods (secondary trigger present)",
            f"secondary={spec.trigger_foods[1]} in_board={spec.trigger_foods[1] in names}",
        )

        # ── 7. trigger predictions ─────────────────────────────────────────
        r = await ac.get("/api/v1/insights/triggers")
        triggers = r.json().get("triggers", []) if r.status_code == 200 else []
        check.record(
            r.status_code == 200 and len(triggers) >= 1,
            "GET /insights/triggers",
            f"status={r.status_code} n_triggers={len(triggers)} "
            f"components={[t.get('component_type') for t in triggers][:5]}",
        )

        # ── 8. lag correlation ─────────────────────────────────────────────
        r = await ac.get("/api/v1/insights/lag-correlation?lookback_days=45")
        corr = r.json().get("correlations", []) if r.status_code == 200 else []
        trigger_corr = any(c["food_name"] == primary_trigger for c in corr)
        check.record(
            r.status_code == 200 and trigger_corr,
            "GET /insights/lag-correlation (trigger correlated)",
            f"status={r.status_code} n_rows={len(corr)} trigger_present={trigger_corr}",
        )

        # ── 9. elimination protocol ────────────────────────────────────────
        r = await ac.post(
            "/api/v1/protocols/start", json={"protocol_type": "low-fodmap"}
        )
        avoid = r.json().get("foods_to_avoid", []) if r.status_code == 201 else []
        check.record(
            r.status_code == 201 and len(avoid) > 0,
            "POST /protocols/start (low-fodmap)",
            f"status={r.status_code} foods_to_avoid={len(avoid)}",
        )

        # ── 10. clinician PDF ──────────────────────────────────────────────
        r = await ac.get("/api/v1/reports/clinician-pdf?lookback_days=45")
        is_pdf = (
            r.status_code == 200
            and r.headers.get("content-type", "").startswith("application/pdf")
            and r.content[:5] == b"%PDF-"
        )
        check.record(
            is_pdf,
            "GET /reports/clinician-pdf (valid PDF)",
            f"status={r.status_code} bytes={len(r.content)} "
            f"ctype={r.headers.get('content-type')}",
        )

    # Clean up the throwaway user so the loop leaves no residue.
    async with async_session_factory() as session:
        await session.execute(
            text("DELETE FROM users WHERE id = :id"), {"id": E2E_USER_ID}
        )
        await session.commit()
    await engine.dispose()

    print("=" * 64)
    verdict = "PASS" if check.all_passed else "FAIL"
    print(f"E2E RESULT: {verdict} — {check.summary()}")
    print("=" * 64)
    return 0 if check.all_passed else 1


def _redact(db_url: str) -> str:
    if "@" in db_url and "://" in db_url:
        scheme, rest = db_url.split("://", 1)
        creds, host = rest.split("@", 1)
        user = creds.split(":", 1)[0]
        return f"{scheme}://{user}:***@{host}"
    return db_url


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Verify the full E2E log->insight loop.")
    parser.add_argument(
        "--db-url",
        default=os.environ.get("DATABASE_URL", _DEFAULT_DB_URL),
        help="Async SQLAlchemy URL for a LOCAL/test DB (default: foodai_test)",
    )
    parser.add_argument("--kb-path", default=str(_DEFAULT_KB_PATH), help="Path to KB JSON")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if "localhost" not in args.db_url and "127.0.0.1" not in args.db_url:
        raise SystemExit(
            "Refusing to run E2E against a non-local DB. Point --db-url at a local/test DB."
        )
    if not os.path.isfile(args.kb_path):
        raise SystemExit(f"KB file not found: {args.kb_path}")
    sys.exit(asyncio.run(run_e2e(args.db_url, args.kb_path)))


if __name__ == "__main__":
    main()
